name: 🚀 Deploy to FTP

on:
  push:
    branches:
      - main # Replace with your main branch or branches you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install git-ftp
        run: |
          sudo apt-get install git-ftp  # Install git-ftp on Ubuntu
        
      - name: Configure git-ftp
        run: |
          git config git-ftp.url "raveeflix.my.id/domains/raveeflix.my.id/public_html/"
          git config git-ftp.user "raveeflix"
          git config git-ftp.password "Natusvincer12@"  # Consider using GitHub Secrets for sensitive information

      - name: Upload changes to FTP
        run: |
          git ftp push  # This will upload only the committed changes to the FTP server
