name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true  # Checkout submodules

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --minify

      - name: Fetch the list of changed files
        run: |
          git fetch --prune
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "$CHANGED_FILES" > changed_files.txt

      - name: Deploy only changed files
        run: |
          while IFS= read -r file; do
            if [ -f "public/$file" ]; then
              lftp -c "set ftp:list-options -a;
              open ${{ secrets.FTP_SERVER }};
              user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }};
              lcd public;
              cd /domains/raveeflix.my.id/public_html/;
              put -O /domains/raveeflix.my.id/public_html/ public/$file; bye"
            fi
          done < changed_files.txt