name: FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true  # Checkout submodules

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo site
        run: hugo --minify

      - name: Generate list of changes
        run: |
          git diff --name-only HEAD^ HEAD > changes.txt

      - name: Deploy only changed files
        run: |
          while read file; do
            lftp -c "set ftp:list-options -a;
            open ${{ secrets.FTP_SERVER }};
            user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }};
            lcd public;
            cd /domains/raveeflix.my.id/public_html/;
            mirror --reverse --continue --delete --verbose $file; bye"
          done < changes.txt